export const productosLince = [
  { name: "Bloque de Melaza Pipo", type: "Producto" },
  { name: "Bloque de Melaza Pipo - Bovino", type: "Producto" },
  { name: "Bloque de Melaza Pipo - Bovino - Mg", type: "Producto" },
  { name: "Bloque de Melaza Pipo - Ovino", type: "Producto" },
  { name: "Bloque de Melaza Pipo - Equino", type: "Producto" },
  { name: "Levadura Deshidratada Tulev", type: "Producto" },
  { name: "Mela Dry", type: "Producto" },
  { name: "Concentrado de Proteina de Soja - Feed Grade", type: "Producto" },
  { name: "Fosforo de Origen Vegetal", type: "Producto" },

  { name: "Levadura de Cerveza", type: "Subproducto" },
  { name: "Solubles de Destileria Concentrados", type: "Subproducto" },
  { name: "Melaza de Cana", type: "Subproducto" },
  { name: "Gluten Feed", type: "Subproducto" },
  { name: "Burlanda de Maiz", type: "Subproducto" },
  { name: "Malta Humeda", type: "Subproducto" },
  { name: "Cascara de Citrus", type: "Subproducto" },
  { name: "Germen de Maiz", type: "Subproducto" },
  { name: "Burlanda de Maiz (Seco)", type: "Subproducto" },
  { name: "Lex de Maiz Pellet", type: "Subproducto" },
  { name: "Gluten Feed Pellet", type: "Subproducto" },
  { name: "Trigo Pellet", type: "Subproducto" },
];
